services:
  kong-database:
    image: postgres:13
    networks:
      - kong-net
    ports:
      - 5432:5432
    env_file:
      - kong-database.env

  kong-database-config:
    depends_on:
      - kong-database
    image: kong/kong-gateway:3.7.0.0
    networks:
      - kong-net
    entrypoint: ["kong", "migrations", "bootstrap"]
    env_file:
      - kong-database-config.env

  kong-gateway:
    depends_on:
      kong-database-config:
        condition: service_completed_successfully
    image: kong/kong-gateway:3.7.0.0
    networks:
      - kong-net
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:8443:8443
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8444:8444
      - 127.0.0.1:8002:8002
      - 127.0.0.1:8445:8445
      - 127.0.0.1:8003:8003
      - 127.0.0.1:8004:8004
    env_file:
      - kong-gateway.env

  crudpy:
    build: .
    image: python-api
    ports:
      - 127.0.0.1:5000:5000
    networks:
      - kong-net

  
networks:
  kong-net:
    name: kong-net
